#!/usr/bin/env bash

set -euo pipefail

OUT_FILE="${OUT_FILE:-}"
NETWORK="${NETWORK:-obtctestnet}"
LISTEN_ADDR="${LISTEN_ADDR:-}"
RPC_LISTEN_ADDR="${RPC_LISTEN_ADDR:-}"
RPC_USER="${RPC_USER:-obtc}"
RPC_PASS="${RPC_PASS:-change-me-in-env}"
ENABLE_EXPIRYINDEX=1
ENABLE_NOTLS=1
ADDPEERS="${ADDPEERS:-}"

usage() {
    cat <<EOF
Generate a minimal btcd config for OBTC testnet or mainnet-candidate.

Usage:
  $0 [options]

Options:
  --network <name>            OBTC network: obtctestnet or obtcmainnet (default: obtctestnet)
  --network=<name>
  --out <path>                output file path (default: ./phase6-<network>.conf)
  --out=<path>
  --listen <host:port>        P2P listen address (default: testnet 0.0.0.0:19527, mainnet 0.0.0.0:9527)
  --listen=<host:port>
  --rpclisten <host:port>     RPC listen address (default: testnet 127.0.0.1:19528, mainnet 127.0.0.1:9528)
  --rpclisten=<host:port>
  --rpcuser <user>
  --rpcuser=<user>
  --rpcpass <pass>
  --rpcpass=<pass>
  --addpeers <csv>            comma-separated peers host:port
  --addpeers=<csv>
  --disable-expiryindex       do not emit expiryindex=1
  --tls                        do not emit notls=1
  -h, --help                  show this help

Examples:
  $0 --rpcuser=u --rpcpass=p --addpeers=seed1:19527,seed2:19527
  $0 --out /etc/obtc/testnet.conf --listen=0.0.0.0:19527 --rpclisten=127.0.0.1:19528
  $0 --network=obtcmainnet --out /etc/obtc/mainnet.conf --addpeers=seed1:9527,seed2:9527
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --network)
            NETWORK="$2"
            shift 2
            ;;
        --network=*)
            NETWORK="${1#*=}"
            shift
            ;;
        --out)
            OUT_FILE="$2"
            shift 2
            ;;
        --out=*)
            OUT_FILE="${1#*=}"
            shift
            ;;
        --listen)
            LISTEN_ADDR="$2"
            shift 2
            ;;
        --listen=*)
            LISTEN_ADDR="${1#*=}"
            shift
            ;;
        --rpclisten)
            RPC_LISTEN_ADDR="$2"
            shift 2
            ;;
        --rpclisten=*)
            RPC_LISTEN_ADDR="${1#*=}"
            shift
            ;;
        --rpcuser)
            RPC_USER="$2"
            shift 2
            ;;
        --rpcuser=*)
            RPC_USER="${1#*=}"
            shift
            ;;
        --rpcpass)
            RPC_PASS="$2"
            shift 2
            ;;
        --rpcpass=*)
            RPC_PASS="${1#*=}"
            shift
            ;;
        --addpeers)
            ADDPEERS="$2"
            shift 2
            ;;
        --addpeers=*)
            ADDPEERS="${1#*=}"
            shift
            ;;
        --disable-expiryindex)
            ENABLE_EXPIRYINDEX=0
            shift
            ;;
        --tls)
            ENABLE_NOTLS=0
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            usage
            exit 1
            ;;
    esac
done

case "${NETWORK}" in
    obtctestnet)
        LISTEN_ADDR="${LISTEN_ADDR:-0.0.0.0:19527}"
        RPC_LISTEN_ADDR="${RPC_LISTEN_ADDR:-127.0.0.1:19528}"
        ;;
    obtcmainnet)
        LISTEN_ADDR="${LISTEN_ADDR:-0.0.0.0:9527}"
        RPC_LISTEN_ADDR="${RPC_LISTEN_ADDR:-127.0.0.1:9528}"
        ;;
    *)
        echo "[ERROR] --network must be obtctestnet or obtcmainnet" >&2
        exit 1
        ;;
esac

if [[ -z "${OUT_FILE}" ]]; then
    OUT_FILE="$(pwd)/phase6-${NETWORK}.conf"
fi

mkdir -p "$(dirname "${OUT_FILE}")"

{
    echo "# Generated by scripts/phase6/gen_testnet_conf.sh"
    echo "# Review and rotate credentials before production usage"
    echo
    echo "${NETWORK}=1"
    echo "listen=${LISTEN_ADDR}"
    echo "rpclisten=${RPC_LISTEN_ADDR}"
    echo "txindex=1"
    if (( ENABLE_EXPIRYINDEX == 1 )); then
        echo "expiryindex=1"
    fi
    if (( ENABLE_NOTLS == 1 )); then
        echo "notls=1"
    fi
    echo "rpcuser=${RPC_USER}"
    echo "rpcpass=${RPC_PASS}"

    if [[ -n "${ADDPEERS}" ]]; then
        IFS=',' read -r -a peers <<<"${ADDPEERS}"
        for peer in "${peers[@]}"; do
            [[ -z "${peer}" ]] && continue
            echo "addpeer=${peer}"
        done
    fi
} >"${OUT_FILE}"

echo "[OK] config generated: ${OUT_FILE}"
